### ISSUE TITLE
 fetch  played tactics puzzles are missing

### ISSUE THREAD

**Issue by problemadder** [pwenker/chessli2#1]
Hi, thanks for the great work. Its amazing! I only have one question. I assume the hugging face version has not the same functionality like "installing" it on the own system? Correct?
If i use the hugging face version no played tactics are exported? Am i missing something?
And are there any hints/steps to install locally. Thanks again and keep up the great work

**Comment by pwenker** [comment]
Hi @problemadder ! 

Tactics support will come soon. Hopefully I can implement it next week :) 
Also the instructions for a local installation setup are going to be added soon to the repository! 
I'll comment in this issue, as soon as I am finished!

**Comment by jpfreiire** [comment]
> Hi @problemadder !
> 
> Tactics support will come soon. Hopefully I can implement it next week :) Also the instructions for a local installation setup are going to be added soon to the repository! I'll comment in this issue, as soon as I am finished!

Hey @pwenker , I just wanted to thank you for the amazing work and open-access tool you developed! One day I commented on Chessli, the first tool you developed, that I wasn't able to install it on my computer and you replied saying that you would fix it and create a better one that would work for non-technical people like me, and here it is, Chessli 2.0! Thank you so much for your effort and for this amazing and free tool! Hugs from Brazil, I felt the need to thank you for your effort.❤️

**Comment by pwenker** [comment]
@problemadder: 

1. I added tactics support! 
2. I added instructions for local setup and programmatic access: 
https://github.com/pwenker/chessli2?tab=readme-ov-file#local-deployment-

Feel free to open a new issue, if something comes up :)
