### ISSUE TITLE
Tag Support for Tactics

### ISSUE THREAD

**Issue by problemadder** [pwenker/chessli2#3]
Hi pwenker,
tactics Anki Import works great! Thanks again for the great work. Looking forward to using it a lot in the future.
A cool feature would be to write the "theme notes" into the tag line when importing them. But its supper helpful even without this function

**Comment by pwenker** [comment]
@problemadder  Did I understand you correctly, that you want to be able to not only import the puzzles/tactics, but also the corresponding themes as tags into your anki card? 
Such that you can browse your anki cards according to the themes of the puzzles using the tags? 

![image](https://github.com/pwenker/chessli2/assets/77207944/38e062db-7261-4d3b-839f-0a19863da5fd)

If that's the case, I have just added it! Now when you export the CSVs, they have not only the PGN column, but also a column with the tags. When you import the CSV you can assign the second field to Tags, like this: 

![image](https://github.com/pwenker/chessli2/assets/77207944/d2636bdb-da80-47a9-8062-9286fc4831e8)

Fyi: I have also added another tab to chessli2 where you can download any puzzles from the lichess puzzle database filtered by themes, rating, popularity, number of plays, etc.  :) 
Here is an example where I used it to generate the 1000 best puzzles for each theme: 
https://github.com/pwenker/chessli2/blob/main/docs/best_1000_puzzles_by_theme.md

**Comment by problemadder** [comment]
exactly what i meant! amazing! hope a lot of people appreciate this feature.
